<?php

return [
    'ACTIVE' => 'Active',
    'INACTIVE' => 'Inactive',
    'DEFAULT_STATUSES' => ['Active', 'Inactive'],
    'PHOTO' => 'Photo',
    'KM' => 'Km',
    'DATE_FORMATE' => 'd/m/Y',
    'TIME_FORMATE' => 'H:i',
    'GST' => '5',
    'CGST' => '2.5',
    'SGST' => '2.5',
    'currency_symbol' => '₹',
    'currency_html' => '<span style="font-family: DejaVu Sans; sans-serif;">&#8377;</span>',
    // 'currency_html' => '<i class="la la-rupee"></i>',
    'currency' => 'INR',
    'MEETING_INTERESTED' => 3,
    'MEETING_NOT_INTERESTED' => 2,
    'ADMIN_ROLE_ID' => 1,
    'COMPANY_ROLE_ID' => 2,
    'DISTRIBUTOR_ROLE_ID' => 3,
    'PERCENTADE' => 'Percentage',
    'FIXED_AMOUNT' => 'Fixed Amount',
    'DEFAULT_COUPON_TYPES' => ['Percentage', 'Fixed Amount'],

    'BOOLEANACTIVE' => 1,
    'BOOLEANINACTIVE' => 0,

    'MONTH' => [
        '1' => 'Jan',
        '2' => 'Feb',
        '3' => 'Mar',
        '4' => 'Apr',
        '5' => 'May',
        '6' => 'Jun',
        '7' => 'Jul',
        '8' => 'Aug',
        '9' => 'Sep',
        '10' => 'Oct',
        '11' => 'Nov',
        '12' => 'Dec',
    ],
];
